### ISSUE TITLE
Save state to persistent external storage

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica-automation-tools#2]
The automation tools tracks which datasets have already been transferred to Archivematica by using a SQLite database.   This should be held on external storage so that state is maintained if the container is redeployed.   It also makes it easier to reset and/or monitor the automation tools by editing/querying the database.

**Comment by mjaddis** [comment]
When starting work on this or when there is a fix ready for Jisc to deploy, please update the corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-227

**Comment by lower29** [comment]
Hmm, the use of SQLite is hard-coded into the `transfers.models` module in the automation-tools itself. Therefore we'd need to extend the AT to be able to make use of other database engines, and then update this project to provide the configuration (probably via environment variables) to cause another database engine to be used. I think we'd probably want to use mysql, to reuse the service already used by other Archivematica services.

**Comment by mjaddis** [comment]
For now, maybe just move the transfers.db SQLite file to the NFS server.   The AM tools creates this automatically and if you want to delete the state of the AM tools, i.e. neuralise it, then all you need to do is delete the DB file.  Therefore, sticking it on external storage and making that visible in NextCloud would go a long way to making the tools easier to manage/reset.   I'd agree that making the AM tools use a proper DB would be better, but maybe not just yet?

**Comment by lower29** [comment]
That sounds easier to achieve, yes. No need to change any AT code.

The `databasefile` is read from the config files passed to the `transfers.transfer` module when executed. This is currently `/etc/archivematica/automation-tools/transfer.conf` in the `automation-tools` Docker image. 

This should arguably be configurable (in the same way as other parameters are), but that's not the main issue: the `databasefile` setting is currently `/var/archivematica/automation-tools/transfers.db`. The path **`/var/archivematica/sharedDirectory`** is where the external NFS folder is mounted, however `/var/archivematica/automation-tools` remains local to the container.

We could either add another external volume to the `automation-tools` container (which would be in `rdss-archivematica` repo, not here), or we could change the `databasefile` path to be under the existing `sharedDirectory` folder, if there's somewhere there that it makes sense to put it that doesn't interfere with or cluter existing AM usage.

**Comment by lower29** [comment]
This has already been implemented by https://github.com/JiscRDSS/rdss-archivematica/pull/141, which changes the rdss-archivematica configuration to use an external mount for `/var/archivematica/automation-tools`.

Closing.
